package-as: Aurarium

ignore:
  - README.md

manual-changelog:
  filename: CHANGELOG.md
  markup-type: markdown

embedded-libraries:
  - callbackhandler
  - libdatabroker-1-1
  - libdbicon-1-0
  - libstub

move-folders:
  Aurarium/GoldCurrencyTracker: GoldCurrencyTracker
